### PR TITLE
convert to go module

### PR DESCRIPTION
**Pull request by dweomer**
* remove glide files
* update Dockerfile
* update Makefile
* github.com/edgexfoundry/edgex-go/pkg -> github.com/edgexfoundry/go-mod-core-contracts
* models.DeviceObject -> models.DeviceResource

addresses #28 
depends on edgexfoundry/ci-management#317

Signed-off-by: Jacob Blain Christen <jacob.blain.christen@intel.com>

### CODE REVIEW

**Comment by cloudxxx8** [comment]
there must be a .go file of some sort in the root, otherwise "make test" will fail.
Since we are going to remove version.go, should we add another placeholder?

**Comment by dweomer** [comment]
recheck

**Comment by dweomer** [comment]
> there must be a .go file of some sort in the root, otherwise "make test" will fail.
> Since we are going to remove version.go, should we add another placeholder?

@cloudxxx8 I would prefer to not have to cross streams on this. Given that `make test` is not currently failing can we move forward with this small refactor and then setup an issue to track the removal of `version.go`?

**Comment by dweomer** [comment]
@cloudxxx8 ah, i should've checked the issue list prior to pushing the submit button. i see you've created #30.

**Comment by dweomer** [comment]
@edgexfoundry/device-random-committers all checks have passed

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
