### PR TITLE
Remove DC "property=value" from device.random.yaml

### LINKED ISSUE #43: Remove DeviceCommands "property=value" from device.random.yaml
reference: https://github.com/edgexfoundry/device-sdk-go/issues/247

### PR DESCRIPTION
**Pull request by FelixTing**
Fix: #43 

Signed-off-by: Felix Ting <felix@iotechsys.com>

### CODE REVIEW

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
you haven't cleaned up all the "property=value"

**Comment by cloudxxx8** [comment]
https://github.com/edgexfoundry/device-random/blob/724f6fbec0dc7cd317e00c63210cea7031bdb0d5/cmd/res/device.random.yaml#L93

**Comment by FelixTing** [comment]
> you haven't cleaned up all the "property=value"

sorry for my mistake
updated

**Review by cloudxxx8 — APPROVED** [review]

**Comment by cloudxxx8** [comment]
LGTM

**Pull request merged**
