### PR TITLE
Upgrade to the latest device-sdk and core-contract

### LINKED ISSUE #51: Upgrade to the latest device-sdk and core-contract
Upgrade the lib to use the latest device-sdk and core-contract

### PR DESCRIPTION
**Pull request by weichou1229**
Upgrade the lib to use the latest device-sdk and core-contract

Fix #51

### CODE REVIEW

**Comment by weichou1229** [comment]
recheck

**Comment by weichou1229** [comment]
@MightyNerdEric 
Jenkins can't pass the verification. Could you help check the error?
image

**Comment by weichou1229** [comment]
@jamesrgregg Could you help check the verification error?

**Comment by jamesrgregg** [comment]
@MightyNerdEric this is looking for the codecov.io config.  I thought you did something last week to address these types of errors?

**Comment by eb-oss** [comment]
recheck

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
