### PR TITLE
feat: Add secure MessagBus capability

### LINKED ISSUE #150: Secure MessageBus Connection (Device Random)
Update to Device SDK which has new secure MessageBus capability.
Update configuration.toml appropriately

### PR DESCRIPTION
**Pull request by lenny-goodell**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-random/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?
no secure MessageBus capability

## What is the new behavior?
Secure MessageBus capability added

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by chr1shung — COMMENTED** [review]
Shouldn't we upgrade sdk version to at least `v2.0.0-dev.52` to pick up the secure messagebus commit ?
Also might be a good chance to upgrade to Go1.16 as well ?

**Comment by lenny-goodell** [comment]
> Shouldn't we upgrade sdk version to at least `v2.0.0-dev.52`

Yep, but have another change for the SDK, so will hold for that change.

**Comment by lenny-goodell** [comment]
> Also might be a good chance to upgrade to Go1.16 as well ?

No, need to keep them in separate PRs

**Comment by cloudxxx8** [comment]
it is ready to upgrade device-sdk-go

**Comment by lenny-goodell** [comment]
@hahattan,  Please submit a separate PR for the Go 1.16 change and I will rebase this one after that is merged.
I have put this one on hold due to some rework that is in this PR.
edgexfoundry/device-sdk-go#922

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
